/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inmobiliaria.Vistas;

import Inmobiliaria.AccesoDatos.InquilinoData;
import Inmobiliaria.AccesoDatos.PropietarioData;
import static Inmobiliaria.AccesoDatos.PropietarioData.mostrarMensaje;
import inmobiliaria.Inquilino;
import inmobiliaria.Propietario;
import static inmobiliaria.Vistas.MenuPrincipal.escritorio;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Ian
 */
public class ModificarInquilino extends javax.swing.JInternalFrame {

    private int auxId;
    public ModificarInquilino() {
        super("",false,false,false,false);
        
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }
    
    public ModificarInquilino(Inquilino i) {
        super("",false,false,false,false);
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        auxId=i.getIdInquilino();
        jtDni.setText(i.getDni() + "");
        jtApellido.setText(i.getApellido());
        jtNombre.setText(i.getNombre());
        jtTelefono.setText(i.getTelefono() + "");
        jcbTipo.setSelectedItem(i.getTipo().toString());
        jtCuit.setText(i.getCuit() + "");
        jtLugarTrabajo.setText(i.getLugarTrabajo());
        jtDniGar.setText(i.getDniGarante() + "");
        jtNombreGar.setText(i.getNombreGarante());
        jtSupMin.setText(i.getSupMin() + "");
        jtPrecio.setText(i.getPrecioAprox() + "");
        if (i.getEstado() == 1) {
            jcbEstado.setSelectedIndex(0);
        } else {
            jcbEstado.setSelectedIndex(1);
        }
        jbGuardar.setEnabled(true);
        editar(true);
    }

    public ModificarInquilino( String title, boolean resizable, boolean closable, boolean maximizable, boolean iconifiable) {
        super(title, resizable, closable, maximizable, iconifiable);
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }
    private void editar(boolean v){
        jtApellido.setEnabled(v);
        jtNombre.setEnabled(v); 
        jtTelefono.setEnabled(v);
        jcbTipo.setEnabled(v);
        jtCuit.setEnabled(v);
        jtLugarTrabajo.setEnabled(v);
        jtDniGar.setEnabled(v);
        jtNombreGar.setEnabled(v);
        jtSupMin.setEnabled(v);
        jtPrecio.setEnabled(v);
        jcbEstado.setEnabled(v);
    }
    private void limpiar(){
        jtApellido.setText("");
        jtNombre.setText("");
        jtDni.setText("");
        jtTelefono.setText("");
        jcbTipo.setSelectedIndex(0);
        jtCuit.setText("");
        jtLugarTrabajo.setText("");
        jtDniGar.setText("");
        jtNombreGar.setText("");
        jtSupMin.setText("");
        jtPrecio.setText("");
        jbGuardar.setEnabled(false);
        jcbEstado.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtDni = new javax.swing.JTextField();
        jbVolver = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtCuit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtLugarTrabajo = new javax.swing.JTextField();
        jtDniGar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtNombreGar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtSupMin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(1030, 790));
        setPreferredSize(new java.awt.Dimension(1030, 795));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 76, 139));
        jLabel2.setText("Telefono   :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 100, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 76, 139));
        jLabel3.setText("Modificar Inquilino");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 240, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 76, 139));
        jLabel4.setText("Nombre     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 100, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 76, 139));
        jLabel5.setText("DNI              :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 100, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(35, 76, 139));
        jLabel6.setText("Tipo            :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 100, -1));

        jtTelefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtTelefono.setEnabled(false);
        jtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(jtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 300, 30));

        jtApellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtApellido.setEnabled(false);
        jtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 300, 30));

        jtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtNombre.setEnabled(false);
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 300, 30));

        jtDni.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDniKeyTyped(evt);
            }
        });
        jPanel1.add(jtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 300, 30));

        jbVolver.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 120, 40));

        jbGuardar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 680, 120, 40));

        jbLimpiar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 120, 40));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 76, 139));
        jLabel8.setText("Apellido     :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, -1));

        jtCuit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtCuit.setEnabled(false);
        jtCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCuitKeyTyped(evt);
            }
        });
        jPanel1.add(jtCuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 300, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 76, 139));
        jLabel7.setText("CUIT           :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 100, -1));

        jtLugarTrabajo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtLugarTrabajo.setEnabled(false);
        jtLugarTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtLugarTrabajoKeyTyped(evt);
            }
        });
        jPanel1.add(jtLugarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 300, 30));

        jtDniGar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtDniGar.setEnabled(false);
        jtDniGar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDniGarKeyTyped(evt);
            }
        });
        jPanel1.add(jtDniGar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 300, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(35, 76, 139));
        jLabel10.setText("DNI garante :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 120, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 76, 139));
        jLabel11.setText("Estado :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 90, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 76, 139));
        jLabel9.setText("Nombre garante:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 150, -1));

        jtNombreGar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtNombreGar.setEnabled(false);
        jtNombreGar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreGarKeyTyped(evt);
            }
        });
        jPanel1.add(jtNombreGar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 300, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(35, 76, 139));
        jLabel12.setText("Sup miníma :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 120, -1));

        jtSupMin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtSupMin.setEnabled(false);
        jtSupMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtSupMinKeyTyped(evt);
            }
        });
        jPanel1.add(jtSupMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 300, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(35, 76, 139));
        jLabel13.setText("Precio aprox :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 130, -1));

        jtPrecio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtPrecio.setEnabled(false);
        jtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(jtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 300, 30));

        jbBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contenido/lupa.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 50, 40));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(35, 76, 139));
        jLabel14.setText("Lugar de trabajo :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, -1));

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado.setEnabled(false);
        jPanel1.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 110, -1));

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Comercial", "Habitacional", "Temporario" }));
        jcbTipo.setEnabled(false);
        jPanel1.add(jcbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 160, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        ventanaInquilinos vi=new ventanaInquilinos();
        escritorio.removeAll();
        escritorio.repaint();
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniKeyTyped
         int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtDni.getText().length()>=8){
           evt.consume();
       }
    }//GEN-LAST:event_jtDniKeyTyped

    private void jtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoKeyTyped
        char key = evt.getKeyChar();
        boolean letra = Character.isLetter(key)|| Character.isWhitespace(key);
        if (!letra) {
            evt.consume();
        }
    }//GEN-LAST:event_jtApellidoKeyTyped

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyTyped
        char key = evt.getKeyChar();
        boolean letra = Character.isLetter(key)|| Character.isWhitespace(key);
        if (!letra) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefonoKeyTyped
        int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtTelefono.getText().length()>=11){
           evt.consume();
       }
    }//GEN-LAST:event_jtTelefonoKeyTyped

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiar();
        editar(false);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        if (jtApellido.getText().isEmpty() || jtNombre.getText().isEmpty() || jtDni.getText().isEmpty() || jtCuit.getText().isEmpty() || jcbTipo.getSelectedIndex()==0 || jtTelefono.getText().isEmpty() || jtLugarTrabajo.getText().isEmpty() || jtDniGar.getText().isEmpty() || jtNombreGar.getText().isEmpty() || jtSupMin.getText().isEmpty() || jtPrecio.getText().isEmpty()) {
            mostrarMensaje("Todos o alguno de los campos se encuentran vacios, por favor rellene todos.", "Error al crear Inquilino", "error");
        } else {

            int auxEstado;
            if (jcbEstado.getSelectedIndex() == 0) {
                auxEstado = 1;
            } else {
                auxEstado = 0;
            }
            String auxTipo=jcbTipo.getSelectedItem().toString();
            Inquilino i = new Inquilino(auxId, jtApellido.getText(), jtNombre.getText(), auxTipo, jtLugarTrabajo.getText(), jtNombreGar.getText(), Integer.parseInt(jtDni.getText()), Integer.parseInt(jtCuit.getText()), Integer.parseInt(jtTelefono.getText()), Integer.parseInt(jtDniGar.getText()), Integer.parseInt(jtSupMin.getText()), Integer.parseInt(jtPrecio.getText()), auxEstado);

            InquilinoData.modificarInquilino(i);
            
            editar(false);
            limpiar();

        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtLugarTrabajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLugarTrabajoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtLugarTrabajoKeyTyped

    private void jtDniGarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniGarKeyTyped
        int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtDniGar.getText().length()>=8){
           evt.consume();
       }
    }//GEN-LAST:event_jtDniGarKeyTyped

    private void jtNombreGarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreGarKeyTyped
        char key = evt.getKeyChar();
        boolean letra = Character.isLetter(key)|| Character.isWhitespace(key);
        if (!letra) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNombreGarKeyTyped

    private void jtSupMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSupMinKeyTyped
        int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtSupMin.getText().length()>=4){
           evt.consume();
       }
    }//GEN-LAST:event_jtSupMinKeyTyped

    private void jtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioKeyTyped
        int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtPrecio.getText().length()>=8){
           evt.consume();
       }
    }//GEN-LAST:event_jtPrecioKeyTyped

    private void jtCuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCuitKeyTyped
        int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtCuit.getText().length()>=10){
           evt.consume();
       }
    }//GEN-LAST:event_jtCuitKeyTyped

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        Inquilino i = new Inquilino();
        if (jtDni.getText().isEmpty()) {
            mostrarMensaje("Debe ingresar un DNI para buscar", "Error al buscar Inquilino", "error");
        } else {
            if (InquilinoData.buscarInquilinoPorDni(Integer.parseInt(jtDni.getText()), 0, 1) != null) {
                i = InquilinoData.buscarInquilinoPorDni(Integer.parseInt(jtDni.getText()), 0, 1);
                auxId=i.getIdInquilino();
                jtDni.setText(i.getDni()+"");
                jtApellido.setText(i.getApellido());
                jtNombre.setText(i.getNombre());
                jtTelefono.setText(i.getTelefono()+"");
                jcbTipo.setSelectedItem(i.getTipo());
                jtCuit.setText(i.getCuit()+"");
                jtLugarTrabajo.setText(i.getLugarTrabajo());
                jtDniGar.setText(i.getDniGarante()+"");
                jtNombreGar.setText(i.getNombreGarante());
                jtSupMin.setText(i.getSupMin()+"");
                jtPrecio.setText(i.getPrecioAprox()+"");
                if(i.getEstado()==1){
                    jcbEstado.setSelectedIndex(0);
                }else{
                    jcbEstado.setSelectedIndex(1);
                }
                jbGuardar.setEnabled(true);
                editar(true);
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCuit;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtDniGar;
    private javax.swing.JTextField jtLugarTrabajo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNombreGar;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtSupMin;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
